apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: netboot-guacamole
  labels:
    app: guacamole
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi