apiVersion: v1
kind: Secret
metadata:
  name: guacamole
  namespace: netboot-guacamole
type: Opaque
data:
  database: Z3VhY2Ftb2xl # guacamole
  user_login: Z3VhY2FkbWlu # guacadmin
  user_password: Z3VhY2FkbWlu # guacadmin
  root_password: Z3VhY2FkbWlu # guacadmin